id: P7792A394
initial_creation_type: input
source_metadata:
  title: Lungta Series
  language: de
  description: 'Texts on the theme of Lungta (rlung rta/klung rta) or Windhorse, including
    chants to accompany the raising of prayer flags:'
  volume:
    835731cc9e964fcf9b56127752cdfe4e:
      title: Windhorse Practice of Tārā
      parent: Prayers
    ab8e985566e64a249932cf21a62f34b0:
      title: Raising the Windhorse
      parent: Prayers
    1f04f85cb7ee4f2eaef91ee286148c90:
      title: Prayer to Gyaltsen Tsemö Pung Gyen
      parent: Prayers
    8f7d8647fb734bcc8d0ea1a794fc81cb:
      title: Brief Gesar Windhorse Invocation
      parent: Prayers
    61518ad77477486c95f1f8d5066493e5:
      title: Brief Windhorse Invocation
      parent: Prayers
    a3b1983171b74c54bc4d93d7e7d9c96b:
      title: Daily Lungta Recitation
      parent: Prayers
    fde57be4217d41f88b81527dd192e61d:
      title: Short Windhorse Prayer to Gesar
      parent: Prayers
    16f3b4fd3fe04244a957fec8dc9c5c44:
      title: The Swift Fulfilment of All Wishes—Offering the Flag of Windhorse
      parent: Prayers
    3416c7aeaf9742aab92d2d8cb6418a9f:
      title: Brief Windhorse Practice of Tārā
      parent: Prayers
created_at: '2022-03-01T04:29:20.280135'
last_modified_at: '2022-03-01T04:29:20.280138'
